leethomason/tinyxml2

tinyxml2.cpp
The original checks order was rather pessimistic for no reasons. We expect it to be successful, don't we?
=> Rearrange checks in more natural order

tinyxml2.cpp
This does the same as this PR https://github.com/leethomason/tinyxml2/pull/223, but doesn't try to put everything into few lines of code. Code gets two lines longer but repeated comparisons are eliminated.
=> Get rid of repeated comparisons

tinyxml2.cpp
... plus one unrelated pre-assert
=> More checks inside UTF conversion

tinyxml2.h
This resolves https://github.com/leethomason/tinyxml2/issues/265
=> Remove redundant parameters list

tinyxml2.cpp, tinyxml2.h
This maybe resolves https://github.com/leethomason/tinyxml2/issues/274
=> Pre-asserts to clarify buffer usage

tinyxml2.h
Earlier changes introduced wrong constraints
=> Use proper constraints for int variable

tinyxml2.cpp
Resolves the crash reported in PR 288.
=> Fix null pointer dereference planted in PR287 and reported in PR288

tinyxml2.cpp
This makes code a bit easier to step over and also more expecting possible overflows
=> More asserts in numbers parsing

tinyxml2.cpp, xmltest.cpp
Clear any error from a previous save attempt.
Added a test to make sure it works.
=> Issue 302: clear any previous save error

CMakeLists.txt
=> Define the `DEBUG` macro in CMakeLists.txt

CMakeLists.txt, cmake_uninstall.cmake.in
=> add in support for sudo make uninstall

.travis.yml
This enhancement will automatic check and test the changes done. It will improve the testing capability of component as build can be tested at every pull request before commit.
To enable this feature , you will have to login in https://travis-ci.org/. using github account 
and enable the travis feature for the tinyxml2 library.
It is simple and a pictorial guide is avaliable on https://travis-ci.org/.
You can even see the build logs of each build there.
(I have attached screenshot)
Many other github projects use this feature. Hope it will help tinyxml2 too.
I will delete previous pull request when this is closed.( I hope I got it right this time).
=> Build with travis CI on every pull request or commit

.travis.yml
Add clang compiler to travis build support.
=> Travis also support clang.

tinyxml2.cpp
Fix for issue: [https://github.com/leethomason/tinyxml2/issues/424](https://github.com/leethomason/tinyxml2/issues/424)
=> Fix for Borland C++ Builder 6

tinyxml2.cpp
Fix for issue: [https://github.com/leethomason/tinyxml2/issues/426](https://github.com/leethomason/tinyxml2/issues/426)
=> Fix 2 "Condition is always true" compiler warnings.

CMakeLists.txt
This addresses issue: https://github.com/leethomason/tinyxml2/issues/444
=> Add INCLUDE_DIRECTORIES on the targets for supported cmake versions.

tinyxml2.cpp
This addresses the problem outlined in https://github.com/leethomason/tinyxml2/pull/458
=> Pointer assertion for contract clarity

tinyxml2.h
In the original code:
1. It's not immediately clear whether block should contain chunks or vice versa.
2. "size" and "count" are not very helpful because it's unclear what they belong to.
3. Block contains an array which is called "chunk" instead of "chunks".
4. `&` is applied to expression which is not braced.
5. Struct member access is duplicated many times instead of using an alias.
6. Type is used in `sizeof` where using an expression would be more maintainable.
=> Clarify "block" and "chunk"

tinyxml2.cpp
`DeleteChild()` does the same and also has more debug checks
=> Reuse DeleteChild()

tinyxml2.h
This should resolve https://github.com/leethomason/tinyxml2/issues/448
=> Assertions in string comparison

xmltest.cpp
=> Use correct file pointer

tinyxml2.cpp, xmltest.cpp
This resolves https://github.com/leethomason/tinyxml2/issues/340 and https://github.com/leethomason/tinyxml2/issues/399
=> Declarations should occur before anything else

tinyxml2.cpp, tinyxml2.h, xmltest.cpp
Adds a friendlier API for querying attributes.
=> Friendly API for attribute query.

tinyxml2/test.vcxproj, tinyxml2/tinyxml2.vcxproj
Not quite sure if this is the best fix, but the dll builds don't work at all in the IDE.
=> Fix windows dll build/run

readme.md, tinyxml2.cpp, tinyxml2.h, xmltest.cpp
Review & minor edits to @kezenator line numbering code.
=> Kezenator line numbering

tinyxml2.cpp
Similar checks are already being done for child nodes.
=> Ensure existing attributes are not leaked on attribute insertion

tinyxml2.cpp
Recently added member variables shoul be initialized in constructor
=> Initialize member variables

xmltest.cpp
It certainly won't hurt to test how the file is being opened and read and also initialize the buffer in controlled manner.
=> Check various stages of reading the XML file

xmltest.cpp
Some of the test rely on `Insert???()` returning `addThis`. This should be tested.
=> Test return values from nodes insertion

tinyxml2.cpp
This resolves https://github.com/leethomason/tinyxml2/issues/579
=> Annotate fall throughs with comments

xmltest.cpp
In the current code one check has "expected" and "found" swapped, others are a bit convoluted and harder to read than needed.
=> Cleanup and simplify checks

.gitignore, premake5.lua
- updated .gitignore with the .projects / .artifacts directories.
=> Added premake5 build configuration with projects for Windows & Mac.

tinyxml2.cpp
=> fix "dereference before null check" defect

CMakeLists.txt
fixes issue where CTest is not able to execute the tests on windows systems
=> fixed issue where CTest is executed in the wrong directory

tinyxml2.h
=> Remove dead yet conflicting method

tinyxml2.h
=> Fix Query return type

CMakeLists.txt, Makefile
=> Add support for position independant code compilation

tinyxml2.cpp, tinyxml2.h
Closes #744 
Added support for uint64_t via Unsigned64 family of functions
=> uint64_t / UnsignedInt64 support

xmltest.cpp
Hi ，
When I run the test case  `Programmatic DOM`  , I found that the comment above the case tells the example is 
```
// Test: Programmatic DOM
// Build:
//		<element>
//			
//			<sub attrib="1" />
//			<sub attrib="2" />
//			<sub attrib="3" >& Text!</sub>
//		<element>
```
But when I run the test suite , the log shows 
```
<element>
<sub attrib="0"/>
<sub attrib="1"/>
<sub attrib="2">&amp; Text!</sub>
</element>
[pass] Programmatic DOM [comment][comment]
```
and I alse look into the code , it shows 
```c++
XMLElement* sub[3] = { doc->NewElement( "sub" ), doc->NewElement( "sub" ), doc->NewElement( "sub" ) };
for( int i=0; i<3; ++i ) {
sub[i]->SetAttribute( "attrib", i );
}
element->InsertEndChild( sub[2] );
const int dummyInitialValue = 1000;
int dummyValue = dummyInitialValue;
XMLNode* …
```
=> fix comment in Programmatic DOM test case

xmltest.cpp
When performed the test, I found that class XMLPrinter there were no test cases for 
PushText( ),PushComment() and PushDeclaration().
@leethomason    This PR supplement related test cases.
=> Supplementary test case

.github/workflows/ccpp.yml, .github/workflows/ci-unixish.yml
At least a basic one: running make on ubuntu-latest + macos-latest
=> Add github action

tinyxml2.cpp
=> Fix errors/warnings with hexadecimal format string in sscanf

meson.build
=> Fix type in meson.build

tinyxml2.cpp
Resolves https://github.com/leethomason/tinyxml2/issues/864
=> Add defined(ANDROID) for fseeko defined and android-x86_64

tinyxml2.cpp
On branch to resolve merge conflicts.
=> Fix android build

tinyxml2.cpp, xmltest.cpp
Assertion '_elementPool.CurrentAllocs() == _elementPool.Untracked()' failed.
=> fix assertion

tinyxml2.h
Hey there,
When compiling my project with `-Wsign-conversion` and `-Wsuggest-override` flags I get some annoying warnings (from both clang and gcc).
I tried to fix them here, please have a look.
In case you see a better solution feel free to update. ;)
=> Fix warnings
