leethomason/tinyxml2

- tinyxml2.cpp
Previous changes introduced a useless if-else chain with broken formatting
> Fix formatting, get rid of useless if-else chain

- tinyxml2.cpp
`strchr()` cannot possibly find null character if it was asked to find a semicolon.
> strchr() can only find what is was asked for

- tinyxml2.cpp
- xmltest.cpp
This resolves https://github.com/leethomason/tinyxml2/issues/291
> Resolve crash when printing malformed entities - issue 291

- tinyxml2.cpp
- xmltest.cpp
This stops VisitEnter from segfaulting with an orphan element. Everything else seems to work., with respect to printing.
Added a test that will segfault without the fix.
> Issue 299 - Printing orphan elements

- xmltest.cpp
Similar to test in https://github.com/leethomason/tinyxml2/pull/304 but for `LoadFile()`.
> If LoadFile() fails then subsequent successful LoadFile() must clear the error

- tinyxml2.h
No point in redirecting the call when all is needed is to return a member variable.
> Simplify overengineered code

- tinyxml2.cpp
Enum size is not required to match size of `int`.
> Ensure enum is printed properly

- tinyxml2.cpp
Won't hurt to have patterns listed in the same order as they are searched.
> Order patterns the same way they are searched

- tinyxml2.cpp
Current code instructs to check the first character again when observing `/anything`.
> Detect parsing error earlier when looking at end of tag

- tinyxml2.cpp
Undo the change from https://github.com/leethomason/tinyxml2/commit/4f0c2ffcab133bdf43a480c3391caef9be5acb61 without warning emission
> Range check without clang "always true" warning

- tinyxml2.cpp
Maybe I don't get something but crafting the default printer object at all times looks redundant.
> Avoid unneeded printer object creation

- tinyxml2.cpp
- xmltest.cpp
XML Declarations can only occur at the very beginning of an XML Document.
Test cases added, to check this.
ParseDeep() fixed, to pass test cases.
This fix should close #332
> When parsing XML Declaration, check if it is being added in the correct place.

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
In this patch:
* Add a test case in xmltest.cpp, for `XMLDocument::Value()`
* Handle null pointers in `XMLTest()`
* Fix Issue #323, by bypassing function call
* Clarify explicitly, the meaning of 'empty' in `XMLDocument::Value()` documentation.
> Assert fires when calling xml document  value

- tinyxml2.cpp
I know that the original code follows a nearly idiomatic pattern. However this pattern requires that you have the range check together with the upper limit duplicated and also couple the after-loop check with the loop logic. It's cleaner to make this with an explicitly named flag variable.
> Explicitly check entity was not found

- tinyxml2.cpp
The original code is broken. It starts with `len=512`, doubles it, then if the string is so large it doesn't fit then `len` becomes `-1`  which is then doubled (becomes -2) and that value is passed into `new[]` which most likely makes the program crash with `bad_alloc`.
> Don't use -1 as buffer length

- tinyxml2.cpp
The current comment fails to mention that the warning is specific to VC. Also you cannot imagine how surprised I was when I rewrote this "properly", compiled with VS2012 and saw no warning - turns out MS folks simply turned it off by default. This should be proper documented to ensure clean compilation on older versions.
> Better document warning suppression code

- tinyxml2.cpp
- tinyxml2.h
This resolves https://github.com/leethomason/tinyxml2/issues/351 by explicitly using `Name()` and `name` every time element name is meant.
> Use "name" for element name

- CMakeLists.txt
Currently only shared library is being built or static library is being build
No option to build both libraries simultaneously.
After this patch : 
By Default shared libs are built
To build static library also configure  cmake with -DBUILD_STATIC_LIBS:BOOL=ON
To build only static library configure cmake with -DBILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON
> Build tinyxml2 as static library

- tinyxml2.cpp
Turns our template functions can only have default parameter values in C++11, so I had to use a templated class class for that. I actually used struct for default public access.
> Get rid of -Wtype-limits warning

- .travis.yml
- appveyor.yml
- readme.md
Added configuration file for [appveyor service](https://ci.appveyor.com), the service is based on windows.
Here is the log: https://ci.appveyor.com/project/Chocobo1/tinyxml2/build/1.0.2
Added building on OS X on TravisCI. Log here: https://travis-ci.org/Chocobo1/tinyxml2/builds/83310669
Preview status badges (you haven't registered on appveyor, so currently it's not displaying status icon but fallback text): https://github.com/Chocobo1/tinyxml2/blob/travis/readme.md
> CI improvements

- tinyxml2.cpp
This should address the problem claimed in https://github.com/leethomason/tinyxml2/pull/400
> Assertion in StrPair::SetStr()

- tinyxml2.cpp
Added call to Unlink in XMLNode::DeleteChild() so that references to
node are removed before memory is unallocated. This will ensure the
child is removed from parent and that no pointers are referring to the
unallocated memory. (Code is now aligned with the code in
XMLNode::DeleteChildren() )
> Error fix DeleteChild

- tinyxml2.cpp
It won't hurt to explain that there're no negative return values to expect from `ftell()` other than already handled `-1L`. This may save if there's an stdlib behaving unexpectedly.
> Assert to ensure ftell() behaves as expected by later code

- Makefile
This patch updates the Makefile to allow building TinyXML2 as a static library on *nix, mimicking Windows' Visual Studio project's behavior.
I tried to keep the Makefile as simple as possible, following the style that was present.
I tried avoiding the line ```$(AR) $(ARFLAGS)s $@ $^```, but the ```s``` was required to build it as a static lib (the default arguments of AR doesn't include that ```s```)
As a plus, I added a new rule to easily rebuild the project.
If you like the idea/patch but want something changed, please, tell me and I'll update it :)
I hope this helps! :smile:
> Updated Makefile to allow building TinyXML2 as a static library

- Makefile
Renamed ```tinyxml2.a``` to ```libtinyxml2.a```, to allow proper linking using the ```-l``` flag on gcc.
> Standardized static library output name

- tinyxml2.cpp
C++Builder doesn't handle well member function specialization (`LongFitsIntoSizeTMinusOne<false>::Fits(unsigned long)`) but a class template specialization seems to work (`template<> struct LongFitsIntoSizeTMinusOne<false>`).
This doesn't imply redundant code since `LongFitsIntoSizeTMinusOne<T>` contains a single method.
> Fixes issue #425

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
Adds int64 support across the API.
Future notes:
- This introduces a long overdue requirement on stdint.h. In the future, I'd like to migrate all the apis to the stdint types. But that is a big change for one PR.
- The inter-line formatting has changed. `foo( int a )` is now `foo(int a)` consistent with Microsoft's standard. Again, I may change that globally in a future PR.
> Add int64 support

- CMakeLists.txt
- tinyxml2.h
Improve definition of `TINYXML2_LIB` to specify default symbol visibility on appropriate platforms, allowing consumers to build with `-fvisibility=hidden`. Modify our own build to build with `-fvisibility=hidden` by default (if CMake is sufficiently new).
The updated definition of `TINYXML2_LIB` follows the same pattern used in other places (at least in [swig](https://github.com/swig/swig/blob/master/Lib/swiglabels.swg#L69) and [vivia](https://github.com/Kitware/vivia/blob/master/CMake/gen-export.cmake#L68)), so there is cause to believe the relatively simplistic check to decide how to define it should be sufficient for most platforms. (Support for GCC 3.x or older was left out as these are beyond ancient at this point.)
Fixes #461.
> ELF visibility

- tinyxml2.cpp
Surrounding code uses `node` pointer, no reason to do otherwise here
> Unify node deletion

- tinyxml2.cpp
The original comment is way too wordy. Also no `nullptr` here.
> Make comment more concise

- tinyxml2.cpp
- xmltest.cpp
As it says, fixed the related SetAttribute overload, and modified xmltest.cpp accordingly.
EDIT: AAA not 399, #270. Darn
> Bool true/false rather than 0/1 : #399

- tinyxml2.h
"need flush" is being set, so `GetStr()` assertions will surely fire if any of the pointers is null.
> Pointer assertions for substring

- tinyxml2.cpp
It's quite weird to see pointers to non-const commented as "read pointers"
> Use const where const is enough

- tinyxml2.h
Pre- and post- manipulations are used with no clear pattern in original code. Just using pre- forms everywhere makes it a bit clearer.
> Unify increments and decrements

- tinyxml2.cpp
- tinyxml2.h
The original code contains both `*p++=something` and `*p=something;++p` pieces with no clear pattern. This splits access and adjustment into distinct statements for clarity and ease of debugging.
> Split access and pointer adjustment

- tinyxml2.cpp
`p` is dereferenced on each loop iteration, no harm in clarifying that with assertions
> Loop invariant pointer assertions

- tinyxml2.h
The `XML_NO_ERROR` return type was removed in commit [855362](https://github.com/leethomason/tinyxml2/commit/8553625730abec2467044b0bb2898b7c4f1114a3). This change updates the documentation to reflect that.
> Update comments to reflect single successful return type

- tinyxml2.cpp
GCC 5+ will generate "error: comparison is always true due to limited range of data type" when -Wextra is used because PowerPC by default uses unsigned char, so it can never be less than 0.
> Fix warning on PowerPC

- .gitignore
- tinyxml2/test.vcxproj
- tinyxml2/tinyxml2.vcxproj
Output conflicted from test and tinyxml2 projects because they shared output directories. Fixed by adding project name as a part of the path and standardized across all platforms/configs.
> Fixes for Visual Studio builds and gitignore output

- tinyxml2.cpp
Conversion from unsigned to signed is implementation defined for out of range values but conversion from signed to unsigned is well-defined.
> Avoid cast to signed integer type

- tinyxml2.cpp
`Identify()` never returns null pointers. A post-assertion makes it clearer.
> Pointer post-assertion

- tinyxml2.h
It's `_node == 0 ? 0 : _node->Something()` in some cases and `_node ? _node->Something() : 0` in other cases for no obvious reason. This uses the latter option everywhere.
> Unify null pointer checks

- tinyxml2.cpp
- tinyxml2.h
There're two pieces of code for creating attribute objects. The only difference is when `SetTracked()` is called. Looks like there's not much difference where it is called, so this code can be extracted and reused.
> Reuse attribute creation code

- readme.md
- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
Row/column of current element / error? #26 
Supported reporting the row of errors, all nodes, and all attributes.
Column information is not supported.
> Row/column of current element / error? #26

- tinyxml2.h
This is a newly added member variable. It should be initialized in the constructor.
> Initialize member variable

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
Allow the string for boolean serialization to be set, so you can write "1"/"0" instead of "true"/"false", etc. Addresses #507
> Bool serialization.

- tinyxml2.cpp
- tinyxml2.h
This consolidates all necessary checks and wiring up in one function for all node types.
I could use `MemPool` type for parameter but that would yield a virtual call on some compilers and also prevent a static size check which is not desirable.
> Extract and reuse nodes creation code

- tinyxml2.cpp
- tinyxml2.h
Currently the variable name for whitespace mode is rather unclear. The constructor also lacks parameter name.
> Clearer variable name

- tinyxml2.cpp
C6011 is "derefencing potentially null pointer". This never actually happens and so it's a false positive from Visual Studio code analysis. The warning is emitted on the line that assigns `_memPool` member. Assertion suppresses the warning and makes code behavior clearer.
> Suppress C6011 code analysis false positive warning

- tinyxml2.cpp
Other `ShallowEqual` methods already have such assertion.
> Pointer assertion

- tinyxml2.cpp
- tinyxml2.h
Current code uses `int` instead of enum. This brings no advantages and reduces readability and type safety.
> Fully use enum

- tinyxml2.cpp
- tinyxml2.h
In the current code variable names are sometimes unclear and sometimes missing. This adds/clarifies them.
> Clarify variable names

- CMakeLists.txt
- appveyor.yml
- xmltest.cpp
In order to to make xmltest a little more cross platform friendly, this PR replaces the calls to `mkdir()` with CMake commands to create the test output directory
> Refactor test resources: Use CMake to replace mkdir()

- CMakeLists.txt
It's a pretty common idiom these days (on Windows at least).
For me, this would help with a [problem I'm having with vcpkg](https://github.com/Microsoft/vcpkg/issues/1028).
> Add "d" library suffix for debug builds

- tinyxml2.h
This literally checks that we actually have the target large enough to contain all the stuff being copied. Just in case.
> Ensure no overrun before copying

- CMakeLists.txt
With this addition of cmake export, users can now use find_package(tinyxml2) in config mode, meaning no more Findtinyxml2.cmake is needed!!
To demonstrate the convenience of this feature, first clone, build, and install tinyxml2
``````
git clone https://github.com/jasjuang/tinyxml2
cd tinyxml2
mkdir build
cd build
cmake ..
sudo make install
``````
Now go to your own repo and then create a CMakeLists of your own that looks something like
``````
cmake_minimum_required(VERSION 3.5)
project(tinyxml2Example)
set(PROJECT_SRCS
${PROJECT_SOURCE_DIR}/tinyxml2Example.cpp
)
find_package( tinyxml2 REQUIRED )
add_executable(${PROJECT_NAME} ${PROJECT_SRCS})
target_link_libraries(${PROJECT_NAME} tinyxml2)
``````
That will just work! A step by step to reproduce this will be something like
``````
mkdir …
> Resolve issue #526

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
The only actual memory leak, that I'm aware of, is string memory that gets leaked from XMLNodes that are created but never put back in the XMLDocument. That's an odd, but annoying, case. This PR tracks "unlinked" nodes and they are now cleaned with the document.
This PR is a squashed version of #559
> Fix rare memory leaks

- xmltest.cpp
Once there's no code that's known to leak anything it makes sense to check for no leaks in the test.
> Programmatically check no leaks are reported in the VC++ debug heap

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
The copy / clone behavior is more subtle than I would like, since cloning a document and and node is a little different. I elected to use 2 new methods:
- XMLNode::DeepClone()
- XMLDocument::DeepCopy()
Rather than an all in one solution.
> Support clone (deep copy) of XMLDocument and XMLNode

- tinyxml2.cpp
- tinyxml2.h
Current parameter name just restates it's a document (which we already know because it's of type "document").
> Better parameter name

- CMakeLists.txt
When building ONLY the static library, some errors occur due to misnamed targets in the CMake file.
Build the library with
```
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(BUILD_STATIC_LIBS ON CACHE BOOL "")
set(BUILD_TESTS ON CACHE BOOL "")
```
for the error to occur
> CMake fix for static library only build

- xmltest.cpp
`err` cannot possibly be changed by `FirstChildElement()` call so it's clearer to test it as early as possible,
> Test parsing result as early as possible

- xmltest.cpp
Current code sometimes has "expected" and "found" swapped in `Test()` calls. This also changes code that unnecessarily uses `int` instead of `XMLError`.
> "Found" and "expected" were swapped in some tests

- .travis.yml
- CMakeLists.txt
This PR makes it so that `make test` runs `xmltest`. It also deprecates `BUILD_TESTS` in favour of the more standard `BUILD_TESTING` variable name which is provided by `CTest` instead.
> Use CTest to add xmltest as a testcase so `make test` works

- xmltest.cpp
The current code has the string duplicated so it's not immediately clear it's the same string both times.
> Extract duplicated text string

- xmltest.cpp
Since many of the tests reopen files generated under resources/out
to reuse as input without performing error checking, explicity
create directory to mitigate segfaults.
> xmltest: create dir resources/out to avoid crashes

- xmltest.cpp
Current code fails to check result of `XMLDocument.Parse()` in many cases.
> Check result of Parse() call

- xmltest.cpp
Current code sometimes fails to check results of `SaveFile()` and `LoadFile()`.
> Check result of LoadFile()/SaveFile()

- xmltest.cpp
The current code fails to check result of `Query???Attribute()`, also sometimes the variable to hold the extracted value is not cleared between calls which can hide errors.
> Test querying attributes thoroughly

- xmltest.cpp
Current code uses the same magic value `10` everywhere. It won't hurt to have two distinct values and have them annotated.
> Use distinct values as default and replacement values

- xmltest.cpp
Current code is indented inconsistently with the surrounding code. I could remove some of the indenting in the block but instead I added curly braces to get clearer scope of the local variable and keep edit history cleaner.
> Indent directives consistently with surrounding code

- xmltest.cpp
Current code produces output that looks like this:
Parsing Release of dream.xml: 1.799 milli-seconds
which reads "parsing release of something" which isn't very clear. Also current code has output duplicated in the code.
> Clarify and simplify test output

- xmltest.cpp
These are some more thorough tests to check that there's no assertion when the element is deleted. It first tests that "owning document" isn't altered upon insertion of the element.
> Test nodes deletion via document

- xmltest.cpp
Current code doesn't check the return value of `Query???Text()` and also delays the checks until all work is done.
> Better tests for Query???Text()

- xmltest.cpp
Current code fails to use "out" subpath for the temporary file which is used for other similar tests. Also it's a good idea to test that the file was actually opened before writing - the file is later opened for reading anyway.
> Cleanup stream mode tests

- xmltest.cpp
Current code only tests the return value of `Parse()`. `ErrorID()` should also be tested.
> Test ErrorID after Parse()

- xmltest.cpp
Current code is illegal - casting a random integer value into a pointer yields undefined behavior. This may cause major portability problems.
> Use valid pointer for user data

- xmltest.cpp
The check might affect the timing, so it should be done only after stopping the stopwatch.
> Stopwatch must be stopped before test check

- xmltest.cpp
Current code uses `int` in place of `bool`, has the file path duplicated and sometimes fails to check `fopen()` return values.
> Cleanup fopen() tests

- tinyxml2.cpp
- tinyxml2.h
This make const XMLDocument be copied to another document. `make test` passes all the test.
> Add 'const' on XMLDocument::DeepCopy. 

- tinyxml2.cpp
Current code repeatedly casts the same variable to the same type. It's unclear whether those must be identical. New code extracts and reuses the cast.
> Extract and reuse conversion code

- contrib/html5-printer.cpp
Instead of: #include <tinyxml2.h> , it is better to go with  #include "tinyxml2.h" so it doesn't search for tinyxml2 library in system libraries but the current directory.
> Update on html5-printer.cpp

- Makefile
- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
Followup to issue #616 
No semantic changes, just added a few missing member initializers in constructors.
> Code cleanup to pass gcc -Weffc++ warnings

- xmltest.cpp
Current code has a number of minor issues:
* same text is parsed twice for no good reason
* variables have lifetime longer than needed which obscures what exactly is being tested
* test description strings are not very clear
* one test uses two handles - one created as a temporary and another one created as a local - and the other test uses one handle all the time and it's unclear why this difference is needed
> Improve handles tests

- Makefile
This PR closes some gaps in the makefile. It follows GNU coding standards and conventions at https://www.gnu.org/prep/standards/standards.html. It is not specific to GNU, and most of the world follows it.
> Add install and uninstall target to Makefile

- xmltest.cpp
* clarify what is being tested to avoid duplicate lines in output
* prevent optimizations based on undefined behavior
> Cleanup ErrorName() tests

- CMakeLists.txt
- Config.cmake.in
After this patch there is only one target: tinyxml2. Whether it is built as a static vs. shared now depends on `BUILD_SHARED_LIBS` only.
This patch also makes sure `TINYXML2_DEBUG` is defined for downstream projects in debug builds and uses `CMakePackageConfigHelpers` to generate the config file.
Fixes #588.
> Unify the CMake targets for static and shared libraries

- CMakeLists.txt
Make resources folder for xml test relative to current source and binary directory. This was failing to build as a nested subrepository, where CMAKE_SOURCE_DIR pointed to a parent folder. For issue #706.
> Issue_706: Make resources path relative to current source and binary dir

- xmltest.cpp
This was found with Cppcheck. `two` was not read. One option would be to just remove it but this test is basically the same as "round 2" so it's clearer to show what `two` must contain.
> Check the element is the last child of the document

- xmltest.cpp
This addresses https://github.com/leethomason/tinyxml2/issues/710 When `XMLText()` is invoked to compare two `int64_t` values those are sliced when printing.
> Fix slicing of int64_t

- tinyxml2.h
Assigment operator takes non-const reference when const reference is the norm.
> Correct assigment interface for StrPair

- tinyxml2.pc.in
Since d89d6d9551e5343de4f70ac534f61c3057713f92, the `tinyxml2.pc` file is missing the install prefix from the `includedir` and `libdir` variables. Here is what I see on my system:
~~~
prefix=/usr/local/Cellar/tinyxml2/7.0.0
exec_prefix=${prefix}
libdir=lib
includedir=include
Name: TinyXML2
Description: simple, small, C++ XML parser
Version: 7.0.0
Libs: -L${libdir} -ltinyxml2
Cflags: -I${includedir}
~~~
This restores the prefix to those variables within the pc file.
Also, I noticed this after testing the new homebrew release of 7.0.0, so I would request a 7.0.1 patch release with this change, assuming that it is accepted.
> tinyxml2.pc.in: restore prefix to lib/include dir

- CMakeLists.txt
Using find_package() with version argument, CMake return wrong version error. This commit resolves this.
> CMakeList.txt: fix wrong version

- tinyxml2.h
XMLPrinter::ClearBuffer shouldn't set _firstElement to true, unless
called after the document is completely generated. Otherwise, the
layout of the XML file is messed up when the buffer is flushed
intermittently. This commit enables this using a default-initialized
parameter, chosen such that the existing behavior remains uneffected.
> Issue 742: allow intermittent calls of XMLPrinter::ClearBuffer

- tinyxml2.cpp
- tinyxml2.h
This PR fixes -Wold-style-cast warnings from g++:
```
In file included from tinyxml2.cpp:24:
tinyxml2.h:1687:63: warning: use of old-style cast to ‘size_t’ {aka ‘long unsigned int’} [-Wold-style-cast]
XMLError Parse( const char* xml, size_t nBytes=(size_t)(-1) );
^
------------
static_cast<size_t> ((-1))
tinyxml2.cpp:104:40: warning: use of old-style cast to ‘char’ [-Wold-style-cast]
static const char LINE_FEED    = (char)0x0a;   // all line endings are normalized to LF
^~~~
----------
static_cast<char> (0x0a)
tinyxml2.cpp:106:44: warning: use of old-style cast to ‘char’ [-Wold-style-cast]
static const char CARRIAGE_RETURN  = (char)0x0d;   // CR gets filtered out
^~~~
----------
static_cast<char> (0x0d)
tinyxml2.cpp: In static member function ‘static void …
```
> Fixed -Wold-style-cast warnings from g++.

- xmltest.cpp
Currently,  the `bomtest.xml`   is saved in `resources` folder,    but the `bomtest.xml`  hasn't be included in the `.gitignore`， and  after I execute 
``` shell
make test
```  
and 
``` shell
make clean
```
the `resources/bomtest.xml`   was marked as `Untracked files ` by  `git`
this PR fixed this issue to place `bomtest.xml` to  `resource/out` folder the same with other test xml files
> adjust path of testfile `bomtest.xml` to `resources/out`

- xmltest.cpp
When performed  the test, I found that there were no test cases for `IntText()` , `UnsignedText()`, 
`BoolText()`, `DoubleText()`, `FloatText()`, `ShallowEqual()`, `PreviousSiblingElement()` and `NextSiblingElement()`.
This PR supplement related test cases.
> Supplementary test case

- CMakeLists.txt
It enables a per component install / packaging with cmake / cpack (but not mandatory)
> Add COMPONENT support at cmake install stage

- tinyxml2.cpp
Ability to handle spaces introduced after inserting text between parent and child nodes
```
<?xml version="1.0"?>
<html>
<head/>
<body>
<div>
<p>Some text in p element           <span>Some text in span element</span>Some other text in p element</p>
</div>
</body>
</html>
```
> fix issue#712

- tinyxml2.cpp
The tokens `TRUE` and `FALSE` are defined in current versions of MSVC, breaking compilation of tinyxml2.cpp in MSVC due to the use of these tokens as variable names in the function `XMLUtil::ToBool`.
Simply changing the variable names to something else resolves the problem.
> Change constants used in 'ToBool' to support MSVC

- tinyxml2.cpp
- tinyxml2.h
Adds a set of convenience functions for building up an XMLElement by pushing new elements at the end
> PushNewChild* family of convenience functions

- .gitignore
This should improve the Linux experience for any Linux developers using the supplied `Makefile`.
> Add Makefile outputs to .gitignore

- tinyxml2.cpp
This implements #786.
TinyXML reads the entire file into a pre-allocated buffer in memory. To
get the buffer size, it uses `fseek()` to seek to the end of the file,
and `ftell()` to get the current byte offset. But because `ftell()`
returns a 32-bit signed value, it can only represent byte offsets, hence
file sizes, up to about 2GB.
To get around this, `fseek` and `ftell` have been replaced by the
`TIXML_FSEEK` and `TIXML_FTELL` macros, respectively, which will resolve
to 64-bit versions of these functions on platforms that have them.
EDIT: my initial commit was based off of a patch I wrote against the original TinyXML code. Reading the TinyXML2 source I realized some checking was added, which doesn't make sense with my changes. I modified the check here. Note that the previous cleverness …
> Added support for files larger than ~2GB

- Makefile
The `clean` doesn't appear to serve a purpose. Make already does dependency tracking, so if files are out of date they will be rebuilt.
The `clean` rule does however cause problems when the test executable already exists. In that case it will delete outputs, including the test executable, and then fail. By the time the test executable was deleted, it was already determined that it was up to date, and so does not get rebuilt. You end up having to run the command twice, each time seesawing between deleting outputs or generating outputs and running the tests.
----
Example problem output from having `clean` as a prerequisite:
```
make test
rm -f *.o xmltest libtinyxml2.a
./xmltest
make: ./xmltest: Command not found
Makefile:45: recipe for target 'test' failed
make: *** [test] Error 127
```
> Remove `clean` before `test` or `check`

- tinyxml2.cpp
This should fix the failing build on VxWorks, as mentioned by @razr in #786.
That said, it doesn't provide the ability to open large files on VxWorks.
> Sharpened check for 64-bit Unix when defining fseek/ftell macros.

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
testcase: 
```xml
<point>
<IntText>  -0x2020</IntText>
<UnsignedText>0x2020</UnsignedText>
<Int64Text> +0x1234</Int64Text>
</point>
```
support hex value, `IntText`, `UnsignedText` and `Int64Text` shouldn't be zero.
> support IntText(),UnsignedText(),Int64Text() for hex value

- tinyxml2.cpp
- tinyxml2.h
Fix indentation of first line when called with `!compactMode` and non-zero `depth`. This fixes a regression introduced by https://github.com/leethomason/tinyxml2/pull/773:
From a test build of `cppcheck` after upgrading tinyxml2:
```
/<<PKGBUILDDIR>>/test/testerrorlogger.cpp:196(TestErrorLogger::ToXmlV2): Assertion failed. 
Expected:                                                                                                           
<error id=\"errorId\" severity=\"error\" msg=\"Programming error.\" verbose=\"Verbose error\">\n
<location file=\"foo.cpp\" line=\"5\" column=\"1\"/>\n                                                  
</error>                                                                                                    
Actual: …
```
> XMLPrinter: Fix first line indentation

- tinyxml2.cpp
I compiled tinyxml2 with the following changes to CMakeLists.txt:
-------------------------------------------------- ------------------------------------------
set (CMAKE_C_COMPILER "/ usr / local / bin / clang10")
set (CMAKE_CXX_COMPILER "/ usr / local / bin / clang ++ 10")
add_compile_options (-g)
add_compile_options (-fsanitize = address, undefined, integer, alignment, bool, builtin, bounds, enum, function, nonnull-attribute, null, object-size, pointer-overflow, return, returns-nonnull-attribute, unreachable, vla-bound , vptr)
set_source_files_properties (tinyxml2.cpp tinyxml2.h
PROPERTIES COMPILE_FLAGS -fsanitize = address, undefined, integer, alignment, bool, builtin, bounds, enum, function, nonnull-attribute, null, object-size, pointer-overflow, return, returns-nonnull-attribute, …
> Suppress UndefinedBehaviorSanitizer warnings

- CMakeLists.txt
If you build tinyxml2 as a static library on Windows, its symbols are exported from any DLL or EXE you create. This generally shouldn't happen.
> cmake: Don't export symbols if building static library

- CMakeLists.txt
Hi, this PR does the following:
- Refactor the `TARGETS_EXPORT_NAME` variable. Previously it was completely unused and there were multiple instances of `${CMAKE_PROJECT_NAME}Targets` copied around the file. This moves the variable definition to the top, and then replaces those all the copy-pasted code with the variable.
- Corrects the comments. Previously there was a comment at the `export()` command that mentioned `find_package`. It's actually the `install(EXPORT...` at the bottom that's related to `find_package`. The `export` command purely generates a script in the build dir.
> cmake: Refactor targets export variable and improve comments

- CMakeLists.txt
- tinyxml2.pc.in
CMakeLists.txt uses `set(CMAKE_DEBUG_POSTFIX "d")` to distinguish
between debug and release lib. Use this postfix also in the
generated **`tinyxml2.pc`** file in case of a CMake Debug build.
This results in the following contents of **`tinyxml2.pc`**
- Release:
`Libs: -L${libdir} -ltinyxml2`
- Debug:
`Libs: -L${libdir} -ltinyxml2d`
> cmake: Fix debug postfix in pkgconfig file

- tinyxml2.h
Changes to allow using the tinyxml2 .h/cpp into a SCU:
- Allowing TIXMLASSERT to be defined before including the main header. This is important to allow custom assert macros.
- Fix for enum bitmask usage
Example usage after this:
`#define TINYXML2_DEBUG (DL_DEBUG || DL_RELEASE)`
`#define TIXMLASSERT(x) DL_ASSERT(x)`
`#include <tinyxml2/tinyxml2.h>`
> Fix for enum in StrPair and TIXMLASSERT define behaviour

- CMakeLists.txt
This makes the locally exported (via `export()`) cmake target script consistent with 
the system exported one (via `install(EXPORT...`). (see line 141)
Previously in the locally (cmake build dir) exported cmake script,
there was no namespace, so the targets would directly be available
in the global namespace. Users would do something like:
include(cmake/tinyxml2Targets.cmake)
target_link_libraries(main tinyxml2)
Now, a namespace is used. Uses will now look like:
include(cmake/tinyxml2Targets.cmake)
target_link_libraries(main tinyxml2::tinyxml2)
This is technically a minor breaking change. It will only affect users
that actually use the *locally* export cmake targets script, which I
expect to be fairly few (note that this is different from the system
exported script). Also, it will only …
> cmake: Use a namespace for the tinyxml2 target in local export

- tinyxml2.cpp
- tinyxml2.h
fixing #826
This introduces an observable change in behaviour, in that previously, if there was no error, the error string variable would point to an actual string, whereas now it is nullptr.
One thing I noticed while running the test cases, the one on line 2000 seems to have a rather misleading message, because as far as I can see `ClearError` is never involved here.
```
XMLDocument doc;
for( int i = 0; i < XML_ERROR_COUNT; i++ ) {
const XMLError error = static_cast<XMLError>(i);
const char* name = XMLDocument::ErrorIDToName(error);
XMLTest( "ErrorName() not null after ClearError()", true, name != 0 );
if( name == 0 ) {
// passing null pointer into strlen() is undefined behavior, so
// compiler is allowed to optimise away the null test above if it's
// as reachable as the strlen() call …
```
> removed overhead of clear error

- meson.build
- meson_options.txt
- readme.md
- setversion.py
Meson is a build system somewhat like cmake, but meant to be easier to use.
It supports many OSes, including all of the major ones, and
a large number of compilers.
My interest isn't really in convincing people to use meson as the
default here, but meson provides a subproject mechanism that can fetch
external projects and build them with the main project in a single configure/compile process. This
is extremely useful for platforms that lack a (competent) package
manager.
As far as I know the meson build does everything the cmake build does,
with one exception: generate the cmake config/version files. meson can
generate these files, but only in simple cases, not using export targets
like tinyxml2 does.
> Add meson build system

- tinyxml2.cpp
fseek64 seems to be specific to glibc and doesn't work an other unix platforms.
(musl and ulibc support it for glibc compatibility)
> Use fseeko and ftello on BSDs

- docs/_config.yml
Force Jekyll to use files whose name begin with an underscore.
@Dfluke suggestion in issue #849 solves the 404 when trying to access _examples_ pages.
Tested to work on my fork: https://mphschmitt.github.io/tinyxml2/_example_2.html
> Fix broken documentation links.

- meson.build
Resources are loaded from the current working directory. By setting the current working directory to the source dir, rather than the out of tree build dir, we can easily pick up the original resources without copying them around during configuration.
> meson: simplify test setup

- tinyxml2.h
The depth recursion limit TINYXML2_MAX_ELEMENT_DEPTH = 100 is quite restrictive for some applications. We encountered it [here](https://github.com/deepmind/mujoco/issues/307), where it is limiting our users from forming simulated chains with more than 100 joints ([here](https://github.com/deepmind/mujoco/issues/263#issuecomment-1128866926) is a video of a simulated chain, for illustration). While we of course accept that some limit is required for safety, we feel that 100 is too small.
This PR proposes to increase it to 500, which matches the depth allowed by other standard parsers, see e.g. [libxml2](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/xpath.c#L131) and [IBM DataPower](https://www.ibm.com/docs/en/datapower-gateway/10.0.1?topic=20-json-parser-limits).
Thanks for your time …
> Increase depth recursion limit

- tinyxml2.cpp
- tinyxml2.h
Added ChildElementCount() to get a count of child elements easier.  Originally suggested by msteiger on sourceforge for original tinyxml.
> Added ChildElementCount()

- tinyxml2.h
`_WIN32` is used for detection Windows. MinGW also defines it, and then causes error.
> fix compiler detection

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
Adds pedantic whitespace mode which preserves text for elements that contain just whitespace
Fixes #242
> Pedantic Whitespace Mode

- CMakeLists.txt
- Makefile
- tinyxml2.cpp
Musl 1.2.4 made the LFS64 interfaces only available when _LARGEFILE64_SOURCE is defined, and they will be removed altogether in Musl 1.2.5. This commit replaces the LFS64 calls with their non-LFS64 versions and defines _FILE_OFFSET_BITS=64, which makes all interfaces 64-bit.
Bug: https://bugs.gentoo.org/905999
> Remove LFS64 calls and set _FILE_OFFSET_BITS=64

- tinyxml2.cpp
Android only supports fseeko+ftello (and their 64-bit versions) for API level 24 and above.
Tested using:
cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=~/Library/Android/sdk/ndk/26.0.10792818/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-22 .
cmake --build build
Failed with:
tinyxml2/tinyxml2.cpp:2380:5: error: use of undeclared identifier 'fseeko'; did you mean 'fseek'?
.../Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/stdio.h:215:5: note: 'fseek' declared here
tinyxml2/tinyxml2.cpp:2390:44: error: use of undeclared identifier 'ftello'; did you mean 'ftell'?
.../Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/stdio.h:216:6: note: 'ftell' declared here
> Use fseek/ftell on Android when api level < 24

- tinyxml2.cpp
The format "%x" is treated as an unsigned int by the GCC compiler. Use static_cast to cast the error to an unsigned int to match the "%x" type. Additionally, replace int(error) with static_cast<int>(error) to avoid the old-style cast warning.
> Fix format error of TIXML_SNPRINTF

- tinyxml2.cpp
In the XMLUtil::ToStr( uint64_t v, char* buffer, int bufferSize ) function, the format specifier %llu was used with a signed long long argument. This caused a type mismatch warning. The argument has been changed to unsigned long long to match the format specifier, resolving the warning.
> Fix format specifier mismatch in XMLUtil::ToStr

- tinyxml2.cpp
- tinyxml2.h
> Update QueryIntValue and QueryUnsignedValue to use int32_t and uint32_t types for better consistency.

- tinyxml2.h
If the DynArray within an XMLPrinter object carries 2 gigabytes of data or more, XMLPrinter::CStrSize returns a truncated result. If a program casts this back to size_t without thought, sign extension leads to bad things(tm).
```c++
int main()
{
tinyxml2::XMLDocument doc;
doc.InsertEndChild(doc.NewDeclaration());
auto root = doc.NewElement("root");
size_t sz = 0x80000002;
auto blank = new char[sz];
memset(blank, ' ', sz);
blank[sz-1]='\0';
root->SetText(blank);
doc.InsertEndChild(root);
tinyxml2::XMLPrinter printer(nullptr);
doc.Print(&printer);
std::string_view sv{printer.CStr(), static_cast<size_t>(printer.CStrSize())};
// sv.size() is way too big, causing overflows on access
std::string dup(sv); // boom
}
```
Fixes: 2.0.2-873-geb3ab0d
> Make DocPrinter support DynArrays larger than 2G

- tinyxml2.h
Several code analysers, like `clang-tidy`, report warnings on ending comment for tinyxml2 namespace. Here is a  clang-tidy 12.0.0 log fragment:
```text
../tinyxml2/tinyxml2.h:2377:2: warning: namespace 'tinyxml2' ends with an unrecognized comment [llvm-namespace-comment]
}       // tinyxml2
^~~~~~~~~~~~~~~~~~
// namespace tinyxml2
../tinyxml2/tinyxml2.h:114:11: note: namespace 'tinyxml2' starts here
namespace tinyxml2
^
```
This pull request is aimed to fix the issue.
> fix tinyxml2 namespaces' ending comment

- tinyxml2.h
There is a typo in the [`XMLNode::DeepClone`](https://github.com/leethomason/tinyxml2/blob/8a519a556afecb3e717a4797615a8bfa49cae10a/tinyxml2.h#L894) description (*"... the memory will be allocated **is** the specified XMLDocument."*). 
```C++
/**
Make a copy of this node and all its children.
If the 'target' is null, then the nodes will
be allocated in the current document. If 'target'
is specified, the memory will be allocated is the
specified XMLDocument.
NOTE: This is probably not the correct tool to
copy a document, since XMLDocuments can have multiple
top level XMLNodes. You probably want to use
XMLDocument::DeepCopy()
*/
XMLNode* DeepClone( XMLDocument* target ) const;
```
This pull request is aimed to fix it.
Thanks.
> Fix: typo in the `XMLNode::DeepClone` description

- tinyxml2.cpp
> Fixed old-style-cast warnings

- CMakeLists.txt
In most cases PkgConfig is not needed in a modern build environment, so add an option to disable it.
> add CMake option to disable PkgConfig install

- tinyxml2.cpp
- xmltest.cpp
This lifts the tests from #1003 (which are quite nice.) The fix in #1003 was based on "not the best" code in TinyXML-2, so this cleans it up a bit, and attempts a tidier fix.
> Fix the potential overflow in char refs

- tinyxml2.cpp
Fix build errors on ARM Compiler 5 (DS-5) by treating the compiler like QNX, Borland C, and the Android NDK for purposes of system header includes.
> Fix ARM Compiler build errors

- xmltest.cpp
Found via `codespell -q 3 -S "./resources/dream.xml" -L currenty,ot,previousy,te,ue`
> fix typos in xmltest.cpp

- tinyxml2.h
In it's current state it does not assert anything as size_t will always be 0 or positive but "-Wtype-limits" will complain about it "warning: comparison of unsigned expression in ‘>= 0’ is always true"
> Remove unnecessary assert >=0 on size_t

- tinyxml2.cpp
- tinyxml2.h
- xmltest.cpp
This is useful for my project, but the feature was already requested in this old feature request: #345 (Avoid greedy apos entity replacement in attributes).
In my use case the single-quote character is both very important and very common in attributes. As a result, the XML became unnecessarily difficult to read because of all the "\&apos;" escaping. This small change allows the XmlPrinter to be customized so that single-quote characters are not escaped in attributes. Since tinyXML uses double-quotes to surround attributes, the resulting document is still parsable. The impact can be seen in [this commit](https://github.com/Malcohol/SeqWires/compare/99a7efce193740e0a965989c7524f33c62420ba4...7cd63b159c4e02bc72e9bee4b2f19de911ca37de#diff-24b59212be6e70014fbe23881c379b181248949c55608d5aecdd57d …
> Optional Apos escaping
